{'A': '10011111111', 'C': '010010111', 'E': '10011111110', 'D': '1001111100', 'F': '01001011011', 'I': '1001111101', '\n': '01001001', 'M': '011001100', 'L': '010010110101', 'N': '01001000', 'Q': '0100101100', 'P': '01001010', 'S': '011001101', 'U': '0110011101', 'V': '1001111110', '.': '111010', ',': '011000', 'a': '0111', ' ': '110', 'c': '10010', 'b': '1001110', 'e': '000', 'd': '01000', 'g': '1110111', 'f': '0110010', 'i': '1111', 'h': '10011110', 'j': '0110011100', 'm': '11100', 'l': '0010', 'o': '01101', 'n': '0101', 'q': '1110110', 'p': '100110', 's': '1000', 'r': '0011', 'u': '1011', 't': '1010', 'v': '010011', 'x': '011001111', ';': '010010110100'}KV˜æù¢ùÒièúÏÁLi5`J…YçGÍñ/^ø×Yš§ª>´LM<æ(ß­?¯e|ÅýìŸ/Ç±“i]Lõ‡qX/ó]1‰Ú`VÄSÆdã¬”n -g–["}èÕg7Æ²£ùxŒ‡›ç\o]~¬Ìq ¯c÷Ì˜ŠùÖWÍÚßšë{ÊËã¬ÎÖ“yÆ¡ºÆô`_ZMTÕóL‚ÐŽÖ:ÌÛ‰‚£â_=âá3bÁŒ/LÓ§Þ†0!ì‚£z14Ç:Óåün×ñ»[ó<²`¾´Í‹2b{ådýfv³N_‘ïÆ2>U|Ê%ƒ?v¿†4ïœÌåý¬V{ïc¤”–v²`±î<Cõ’æñ£ë?biŽh˜ŽÏþ\g9^ífGëßÈŸþu’Ä­Yø+=÷± #-¬´5B1;L
ÏZëqû«õ™·GÄ­\ÉååññšoZ|j‰dÚWS=næéúv·ãå«Ö^‹ZÀÛ“ËËãã&¬‘dOÌÈý{ùï\_8p½CŽ²E‘?3é‰äëZ}]ü˜<V˜Å}ó-¬˜Éý8É´®¦zÇñqƒ&_/«<ŸÓŽ³;Yå»[óLO oLduøæØÏLg/íoÍÇˆ~´þ¯~išu_M=&ªnEñ«Ö^‹ZëO«C¸=ÆŠñ“
ëãLqŒõ«Ö^‹ZÀÞµzËÑkY0]d£qkÓ4é÷ÍÎ³;Z‡&iêõ—¢Ö·=Œ+â)ãLsLØ°câºIIf„n;?ùq™øÂóß{®UpÆ€"ù}Z=sœ¯WÎ³1Ä‚¼dþœn=ŸÆþ³6â`¨ø™ïïY¾þõ‰åëïÖŸ½7åÆ¬ü—çOištìfš¹ŒÓ—áLf@ø¯˜„ªã¬ÌiÎý&¬ÖõžûØÏ§ª>µÅkfhF²£ùx1<½frâ›½½eèµ®³1ìþ5‘?$Ó˜zÇñq”KÑß:Ìík¬ëCqû«õ§ùk~`oY6•ÔÏ]fv³åøýë‰¦9¦²OÕÏ'e5ÓÐë%O<+Œù„S7?¸×Yø[‡&¸ÄÙÍ:øËó§ºÌÛ‰‚£â™´¿­>­àðdËåõfÆ«9¾0¼Ÿ¦ßIª›‘|1¸*ãqìþ0!Àµ|Ð8ÆÅg/íb·ÍÍóEózå¬u§Õ¡ÜOÓo¦lX1¬¨þ^#¤”–mÄÁQñLÚ_ÖŸ„WÎ²¾cžjÊã>õ”K2?^þDýfmÄÁQñLÚ_ÖŸÕïÍ@Šãk7?¸ÞŒåý­ùž˜Î_Úß™?§¿½“õ’Ëøíc]aj0_ãD·Ÿü¸Ê;XëO«@Ñ|Â·„[¡ó'àŒòÎ´7ÍÍ1ÿ>7®d÷/qÖJžxW*¾1¸*ã{ÊËãzÐ4_0¿Ž5n<CàÏÉ´®¦zÖjìg¬W*¸ÀÛ¾p6áZ:É{æ†Ëþ2½7µ0W¯q…n?uøÈøÓ9ÕŸ…­Æ­c+Ä…Yãô|¬®7.:ÉFß]ßê¾0_æyeùÓÛ"øÖT/Ÿ=eøþ´ÿ/íoÍ+8¸Äòõ÷Èi4óÖLE|ë+çY(Ûë¢â_7Öã‹t>iËóäÂ…zøë%}roq¸õ_þ.Ý¯ãLb¾ù¦³¸Í5swÖf„oFüÎ_ÚßŒhiËêÑë¸ñ“Æõ h¾j³›ã¤””©ç€Eq”Kqìþ7køËñùËû[ó=Êš}fhF}3bÁÇ³øë% ´#µŒ/ãFiËð½4ó˜£}"ù}Z=zÓü¿µ¿07¬›Jêg®´ÿ
tš°;[ÓmeŸÈ*4Àˆ-íaŒÓ—â«Œ{ ¨ÐóxV4ištùœ¸¦åø,ù~¬”‚ÐŽÖ4óÎúu­ÆœïÔý¬h
%WVQWVã‹t>düžZ¬æøÃ¸ŠxëOÞ›òãw7OÐûøÓw§‚ Áýb«8Qõ…õ§õ{ó´À¬ë{åó|ëf¯¢â_7Ö€Ž²\ž#<Ôµ<¾¿CeíŽ×¾šo©§ÚÂÖ˜“Vç{ålQ»`{ÖBjliïàWŽ²^ù¡²ÿŒ¯MícLëç\a[Ý~2>4Îugákq«BÊñ!Vxý++ËŽ³1§;ôdÁ}g9_I),íaÜE<`oY§/c]iŒWß0/¬›Jêg¬¢]d D„v±d*¾byzûõ’šMç†âþöOšrö3ë"~I§0<ù¡¤_/«G®yu’Õ¦9¾h¾d4šz>³ðSMX¡VyÑó|K×¾õÖJ6úë¬†“O'éƒ7cI«ÞÆ«9¾2‰1™=Ëç\n
¸ë%«Ls|Ñ|Èi4ô}gà¦4š°%B¬ó£æø—¯|ë¬—7ÆŠñƒ&_/«=Vs|1 #Døíc9ÊôÀˆ-íczõ’,‰ñü\i¬îÉú`Íð½CŒ­V3!}ýëGÖ~
ß4_:Éeüv±…duøæ'•ÇI)3ãTK(–õ–Ö]d£o®u¡žûØcI«µ½o\£µ"ù}Z=XÁ“/—ÕžNÊk§¡‘ÖJ7²N1\ªã(íaYø+øãQ–Ö]d D„v±½h/™7?¸Üz¯Ž´ýé¿.4`më¹úbyzÒj£ø¯d‹"}ßê¾7«ãv·æQ-Çgÿ.:Ó÷¦ü¸Ä‚ÿÒjÀíoYZ¹/Œìb¹UÆLO|¬Ÿ4åýd²þ;XÞº¿Õ|aÖf„oš/™&›Uñ»_Æ³WÞ†16sN¾7­EóLs¬—'ˆÏ5­O/¯ÐÙ{cµçF/¦›êiö°µ¦¤Õ¹Þù[nÆ˜õš›{øÃc¤””£qkQüWö°ÆšÎãz4LN'T}1‹ûÙ>³WÒjÀ•
³Öjìay*¾g9^[Ñâã¬–î$3Öd÷/qšrþ²\Þ1|àmÐ8Æ†‘|¾­»"øÐÒ/—Õ£×+UeGòñ7Î¸ËdOÖŸ„WÎ²¾fOrù×ÖLõ¨þ+ûXÒj÷±”Kz07®´ýé¿.4b«†4¬âãGÖ~
ÅýìŸz±¥gâ¿µŒùÖŸáC®‡ïõ_Ý~#ù™øë% ´#µÚþ2ü~ô`¿Í3NŸ&+×Æã‹t>Q,"ºÉDüÈþëñÍóEóúc(–i«˜Í9~CÍó®5×Y­4ó˜£|¿¸ìÿåÆZ¿Õ|dì¦ºzfhF˜¡¬fGëßÈŸYòM9õ’æñ¤ÕïaŒ†“O&Ë×ß'éƒ7c:ÐÕg7ÆGÊ¯›žÆ€^²ôZÖ³WÁŸ•«ªÎoŽ³1ìþ5Mq“²šéèdÚWS=u§Õ¡Ü;£¾i¬î2‰dÚWS=oäÀÑâºIIHµ–yd{ó(– ÝÜÝ?Cé5QüWÎ²E‘?2vS]=f¯–ÖLa{Uñ‹ûÙ>²£ùÑõŸ‚ºÌÐ1<½eø,;ŠÁŸ¿“GŠc'éƒ7Ó‰ÕY&ž“yÆ¡½fhFrþÖ+&+×Æg.)¬g­C“4ñ{'Ó¯¾aÜWY˜ö"øÇñqžûØczé5{ØÅó·4ÕÌg—Y"ÖZ‡!MX¡VyËûX®²[¸É‚Ëó§²~˜3}7…ÓY'êç«Ö^‹Zë% ´#µŒNÓ²nq‰¦8ÆOéÆ‡ïõ_cPä×f?Y˜ö¦eµ–¬ü¬¨þB45B:ÓêÐîI¼ãPÝ5ÆQ,sÍY\fš¹Ž´ú´;ƒÖT!¿½“àÏcâ´ðT?¬ëW¬½µ”K­?«ßšëÅÆyoš/˜çš²¸Üz¯Ž´øÕËó§±ü\1¬‰ù&œÀô}gà­8Qõ»_ÃÖ¢ùž°gõ§ËøÜz¯†2Ùç–GÊ¯›ŽÏþ\1žûØÍG·zÐ4_2M60¬2ù}Yà¿ÌÈÆºÈi4úIIK›Æ˜Å}ó/ÁazEòú´zê™§ÖKß46_ñ•é½¬i‚½|ëŒ+qû¯ÆGÆ™Î¬ü-n5hC^$*Ï£åeq¹qÖf=ŸÆ8¯™/èÜqœ¿µŠÓ¯¾o\ùüë%ˆYD±é7œjÆÄSÆ«9¾0¦4?ªøÔÓ¦ŸY/fó¾¬÷„[¡ôdþœby\f^¿:ãN'T}u’š.%ó}eùÓØþ.×ZVqqšrý&¯{×¬–_ÇkZ¹ÎWžY~?Ë×ß2õù×fc‰xÞ´Ì¿½â¿µ&¬	P«>²P"B;XÄÙÍ:øÂ+>çç/íb´4‹åõhõÉ‚Éý8ÌåÅ7¬Ì{?Œ;ŠÎr¼ŸÓŒBUq‘ò«æšyÌQ¾“yÆ¡ºësúÉeüv±…üq¨Üx‡ÓÈÖãÄ>+•\h ¬u§Õ¡ÜzÉÙMtô3 _gÌž^_Í_¬”mõÂñ|àmÀÛfc‰xÏ,Ÿ¦ß4åìejæO//ŒÔ{zÉ@ˆ-ícNùÁQ|c(íc]j?ŠþÖ4âuGÓ~tö["}Æ‘|j³›áu¨þ+ûXÜü£µŒò•òq|àmé%%"ÈŸ&ÊãoZ…¸îŽù“_:Êù“õÖH²'Â²M=<é4ó˜£}™éC“\fœ¿¬”‚ÐŽÖ2ÚË9ÊØÈþëñÍèÎ´2`˜Þò²øÒjÀíoY§/ë$YæOrù×ž^¾øçš²¸ë$ZËþoš/Œh˜õÉ‚úÉ‚cqÙÿËï+/ŒO+Ž²E‘>¯Yz-iÇ³øÏ¢@üv±§|à¨¾1¸*ãUœß`D„v±¡æð¬húÏÁY*¾n
¸ÁŸ #Y«õ’,‰ù“_:Êù™øÔ®Ê%Žèï˜žWÊåâ4u§Æ¨–ÄSÆiËð_ã^OÓo¦³¸Ã¸ŠxÂºÓêÐîv¿Œ†“O'ôãþn4‹ã&"¾u•ó(–ªÎoŽ´þ¯~dþœfBûûÖ!*¸ë%—ñÚÆM¥u3ÖLO|¬ŸkëCH¾_V\ëCqÙÿËŒ;ŠëOQ,{ ¨Èi4ò`³­wG|cv¿Œåý¬V Eq¦iÕ}4úÓü(uËdO¾h¾1§‚ Áýa{ûÕ3N«é§™züëŒ˜/®²E‘?1;L
É‚úÃ¸­f¯ƒ&_/«<î¿üë$?4š½ìayme“žåM>’RR-ežY0_YZ¹œ¸¦è˜G÷_ˆþu’,‰ù½¨öáyÖ†“UÀµ|ÇtwÎ²\Þ0¼˜žùY>]d·q!½h/™1ó¬¯š.%ó}u§áó¬¯šëCPä#úczé5`v·¬¿ÖJAhGkóÜ©§“ôÆ¬üžåM<BUqÖJAhGk7ÍÌ+=÷±¸ìÿåÆ™|¾¬ð­Úþ7!úIIŸåý­ù§ª>°!ì‚£@æôn4‹ã¬ÎÖþL+5Ü;ŠÄí0+2ßÞºÉeüv±»_Æd/¿½d_±½w„[¡ò/úÓ÷¦ü¸É‚Äò¸Éú`ÍØÃ¸ŠxÇñqžLh¸—Íõ»[ó¬Í¸˜*> næéúPä×§/Ð™ïï]d‹"~j?ŠþÖÈ÷æºÅr«ŒŸ¦Ý7…ËðYîTÓËñìn×ñ¤Þq¨nã÷WÍ9~¬ü‹çoZ|j‰`CÙFõ•«½dÄ÷ÊÉôš½ìu™gñ»_ÆLÖL(W¯†2m+©ž³ _fÅƒiß8*/˜×ZW¿3ÖCI§¸ñÖJ6úé5QüWÌåý­ùh1§ª>·Ÿü¸Ëk,÷*iá]d D„v±§žwÓ­n4ç~£ø¯íc@Q*¸Â²Š¸Â·„[¡ó'àŒòÕg7ÆÄSÇY(ÛëŸ=÷±“úq¬Õô¬âã#åWÎ²Y¬aÜVyJù¹~t÷Z}ZÁàCjùšrýf>ã‹t?Y˜âA^3'——ÇÆãH¾7º¿I))sxÝÍÓô>¯Yz-k=÷°Æ€CM:ié‰äëz:ÉDüÄòõ÷ÝÍÓô>/ïdýfmÄÁQñ'ôãÅÆÅgZUñ½h/™ëz06ÇY-ÜHeÀ‡²
@ŠáŒ+L¾_Vy0_]iõh/˜Vã‹t>düžYÖ†ù¢ù¦?çÆõÌžåó®:ÌÆœïÂ²m+©ž³œ­dOÉ4æ¦iÓêiÓO­>_ÆãHExÇtwÌëAÇgÿ.4›Î5Çñq¦žso£ë?u™9ß“úqÒiçËðY0¡^¾1Ï5eq…a{ŸÒJJCó&+×Æ Ý"ù}Z=XÉÙMtô3N_½XÒj¦ä_&ŸZ}\/C÷ú¯Çˆ~²Q·×âµzËÑkXEu’öo;êÏÀÞ·®G¿4Í:¯¦ž“W½Œ˜,ø¿½“õ’Ä¬¢YÖ†£ø¯ía5’~®{gñ^²ôZÖù¢ùÖf8WŒ±™øcN'T}g–'•Æzcw7OÐù*¾n<Cõ’ËøícÅÆ‡›Â±¤ÕMÈ¾0î+5ÜŸÓ†3M\Æ'—¯¾u¡ÖH²'Òo8Ô7I«T*ÏYòM9õ™gñ™züëŒ;ŠÌåÅ7GÖ~
Ì½~uÇY›q0T|@Ê%¸Ò/ŒO+Ž³6â`¨ø¸Ò^45B54é¦Æ¬ü¤Þq¨n¦4ôÖIú¹ïGI))²É…
õñ¨rfž_<ÆºÖDü“N`xÖ+•\a}d½›Îú³Ì…÷÷­<ëY«±…n9·Cê³›ã@äÀðî+­?«ß™~qâGñ_ÚÆíštÓÞ†3M\Æ™±`Æù¢ùÖH²'ÞÇˆ}uÒié›oyY|u™Ž$ã9k™ËŠn|›Jêg¬˜ŠùÖWÎ²CóYQü¼F“V¨UždáŒ;ŠÉÙMtô3œ¯2yy||o^²\Þ2‰dÄ÷ÊÉõš»ù04x­0"B;XÜ{?Ž’RR¾º>³ðV_=•«¸öwÎ
‹æOÓoÖK›ÆzÜx‡ÞŒ£µGñ_ÚÆ™§O¥gw—ãúÓðŠùÖWÌëC|Ñ|ÓóãzæOrù×§/År«Œ+YQü„i›i\ï/|—³p–™*yà\ià¨0Ln<Cá[Uñ™¯"v5š¾LÖd÷/q“ôÆ€ŒÈý{ùî=ŸÆdã&(íc¬•<ð®4¬âãLs=nÖüÃ¸Šxc+WqÙÿËŒ±‘ò«çZ…¹¾þõ‹ûÙ>iËØ×X›9§_gñ¢@üv±“úqÖŸWOAƒúÖjùåªÎo“ÈþëñÎ´øÕÒj÷±¦³¸Ëk&0¼p-_7k~jõ—¢Öµ×Z~ôß—D±4Ç3œ¯­>_ÆQ-3NŸÎÞ²\Þ1<½}ôš°;[Ö'•ÃZ¹îTÓÇñq™<¼¾>5×Y"ÈŸIª›‘|`ÏËñìgÇ<Õ•ÆõŽèï›µüu™¡ë<¥|‡]Vs|u’-e¢@üv°Æ'•ÆzÉú`ÍõzËÑkL`¿Ìë{ÊËãpUÃµün;?ùq¸*ã:ÐÝ¯ãÊã¬”‚ÐŽÖ1ÝóLO oXc]h˜Z}\Ó—æ@¾Õë/E­az‡&iáÜSx*ÖõÎ´:IIŸW&+×Æ£ø¯ícqâ
ßÉ£Åu§Æ¨–õ h¾b¹UÆ/ïdìaÜVñÆ£=÷±¡ûýWÆÖŸ/ãóVWeøü;ŠÒjÀ•
³Î_ÚÅ1‰¦9½oZ‹æíoÆ0¼Éååññ¹øc(–ã÷Wë3µ¨þ+ûXÏ}ìg”¯ë‘ïÍÆ‘|g¹SO­?¯e|Ï)_!×ÊãÓYÜbyzû±”K#û¯Ä4j?ŠþÖ:ÌíoFãÕ|d_õ’ÝÄ†€+8¸ÐóxV4}gà­<ëÎÞ’RR-e½‡&ià¿Æ4jõ—¢Ö³9qMëOÂ+çY_2N7º¾ž
ƒõ‘ïÍë@Ñ|Ürn‡Ìž^_ë:Ðë$?2`²aB½|cø¸ëOÂ+çY_3Ë/ÁaYme«Ö^‹ZÌžåó®7®ºÌåÅ7¬‘k,˜/¬O+†3ÊWÈuÑõŸ‚·k~dþœ1¤ÕïcPäÍ<"ºÉsxÓ¾pT_2oq—çO1…î=WÆüëOQ-ë‹çnLE|ë+ãc÷Ìç+Â˜Þ´Ì±ÒJJQ·×@äÀòü~j=¬o]C“4ò`¾°dËåõg”K­>5DµÖ“U7"øÕg7Ãë{ÊËãlu™¡Vqq–ÖZ4ïœÌ‡›ç\u’ZÚÆOéÆrþÖüÜx‡c]i5{ØÍ9Y*yà\dÂ…zøc2ñ…éÄê­ü˜<SÎWÒié5QüWÌ_ÞÉØÏ™=Ëç\oš/›µ¿2‰eùÓÝfc‰xÑõŸ‚·Ïã=oš/™7Î¸Ò³‹ŒŸÓŒ;ŠÍ9Yš¬¨þB0­Çî¯“úq¸õ_d‹"|‡›ç\frâ›“ªÎo&¯{ejäuøæu¡“sûŽ´ýé¿.5Öü/pUÆ'—¯¾ÄSÆí3œ¯¬Í¸˜*> o]"ù}Z=u4é§ÖHµ–¯Yz-kz7Ïã9k~b¹UÇY˜âA^1ü\n?uv4š¨þ«æõÌžåó®0¶5zËÑkZëpUÇY¬MœÓ¯Œ÷ÞÆzÑq/›ëI¼ãPÞ²E‘>rþÖ+•\aYúâ¿µ†3é5QüWÌ÷ÞÆ™±`Ç@